"""user likes table

Revision ID: 2c01ceeefecb
Revises: 7fc0291f0f8d
Create Date: 2024-11-30 18:13:03.198031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c01ceeefecb'
down_revision = '7fc0291f0f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['db_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['db_users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_likes')
    # ### end Alembic commands ###
