"""add post table

Revision ID: 41d67347e332
Revises: 0b4a87c33a7b
Create Date: 2024-11-28 17:31:31.544675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d67347e332'
down_revision = '0b4a87c33a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('db_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_db_posts_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_db_posts_title'))

    op.drop_table('db_posts')
    # ### end Alembic commands ###
