"""authored posts

Revision ID: 7fc0291f0f8d
Revises: 41d67347e332
Create Date: 2024-11-28 20:25:18.689647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc0291f0f8d'
down_revision = '41d67347e332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_author_id', 'db_users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_author_id', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
