"""cascading deletes

Revision ID: b4b9709d36f4
Revises: 2c01ceeefecb
Create Date: 2024-11-30 21:18:04.249794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b9709d36f4'
down_revision = '2c01ceeefecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'db_users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'db_posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'db_users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'db_posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
